"""add race condition safeguards for friend requests and outing invites

Revision ID: 32fc32cf212c
Revises: 5ae75940ae38
Create Date: 2026-09-24 14:09:08.443812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fc32cf212c'
down_revision: Union[str, None] = '5ae75940ae38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add nullable first - existing rows have no value yet, so a straight
    # NOT NULL add would fail against the live table
    op.add_column('friend_requests', sa.Column('low_user_id', sa.Integer(), nullable=True))
    op.add_column('friend_requests', sa.Column('high_user_id', sa.Integer(), nullable=True))
    # backfill every existing row before tightening the constraint
    op.execute(
        "UPDATE friend_requests SET "
        "low_user_id = LEAST(requester_id, recipient_id), "
        "high_user_id = GREATEST(requester_id, recipient_id)"
    )
    op.alter_column('friend_requests', 'low_user_id', nullable=False)
    op.alter_column('friend_requests', 'high_user_id', nullable=False)
    op.create_index('uq_one_active_friendship_per_pair', 'friend_requests', ['low_user_id', 'high_user_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'accepted')"), sqlite_where=sa.text("status IN ('pending', 'accepted')"))
    op.create_unique_constraint('uq_one_invite_per_person_per_outing', 'outing_invites', ['outing_id', 'invitee_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_one_invite_per_person_per_outing', 'outing_invites', type_='unique')
    op.drop_index('uq_one_active_friendship_per_pair', table_name='friend_requests', postgresql_where=sa.text("status IN ('pending', 'accepted')"), sqlite_where=sa.text("status IN ('pending', 'accepted')"))
    op.drop_column('friend_requests', 'high_user_id')
    op.drop_column('friend_requests', 'low_user_id')
    # ### end Alembic commands ###
